spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  root: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace

